### ISSUE TITLE
res.headers.raw() not implemented by whatwg-fetch

### ISSUE THREAD

**Issue by tomasklapka** [rdf-ext/rdf-fetch-lite#1]
This line breaks with `res.headers.raw()` when using rdf-fetch-lite in a browser.
https://github.com/rdf-ext/rdf-fetch-lite/blob/9e574b83aa7d8d80c9ee41feb7141ee01de61dca/lib/patch-response.js#L20
My guess is that the method is not implemented in whatwg-fetch.

**Comment by bergos** [comment]
Fixed in the latest version. `.get()` is used and the values are separated with `.split()`
